### ISSUE TITLE
Can this expression detect if the user is a subscriber?

### ISSUE THREAD

**Issue by Doxmia** [madelsberger/if_StreamlabsParameter#1]
ie if user=subscribed. I can't see a way to do this via SLABS documentation. This way you could make a chat command do one thing if the user is subscribed or another if not.

**Comment by madelsberger** [comment]
Thanks for your interest in the $if script.

To the best of my knowledge it could not do this on its own; as you noted, the bot doesn't provide a way for commands to test permissions in forming their reponses.

However, you can combine $if with another parameter script I've just posted: https://github.com/madelsberger/perm_StreamlabsParameter

    $if('$perm(user, level)', 'yes response', 'no response')

Keep in mind that once you start importing tools like this, the tendency may be to push the limits of command definition as much as you can; but as you do, you'll find that the command responses become hard to understand and maintain.  If you want to implement more complex functionality, you may want to consider using custom Python scripts, as they're better suited to representing involved logic.
